### ISSUE TITLE
english data

### ISSUE THREAD

**Issue by bj0** [Martin-Pitt/dsp-parser#4]
I got your parser to run, but I was wondering if there was a way to pull the english names and descriptions out of the game?

**Comment by Martin-Pitt** [comment]
Sorry about late response but you can find the original english locale data in your Steam folder where your games are installed. DSP has Locale folder where these are stored: `[...]\steamapps\common\Dyson Sphere Program\Locale\`

The locale parser in this project is designed to turn it into a more useful JSON format.

By default the parser currently looks for a Dyson Sphere Program folder next to the folder for the parser. But you can change this in the `scripts/build.mjs` script, replacing:
```
const parser = new DSPParser;
```

with:
```
const parser = new DSPParser("C:\\Program Files (x86)\\Steam\\steamapps\\common\\Dyson Sphere Program");
```
for example or wherever your game is installed at.


You can find previously uploaded parsed files in the /dist/ folder.

items.json contains items which reference names from the locale.json, e.g. the very first item is iron ore which has "name" and "description" properties, we take these lookup strings, which are "铁矿" & "I铁矿" and lookup these values on the locale.json

I'd previously written code on my DSP Ratios project on loading these files and processing the items to translate all the objects:
https://github.com/Martin-Pitt/dsp-prod-ratios/blob/main/src/lib/data.js#L26-L103
